### ISSUE TITLE
filtering_vcf_based_on_depth_and_completenes.pl

### ISSUE THREAD

**Issue by edgarjavi** [mscampbell/Variant_sandbox#1]
This script works, but it also retrieves no variant lines. I think the last ## else statement where the no variant lines are called, if you change the $number_passed  variable to = 0, will only retrieve the variant sites. But I don't know if tis is really what we want.

Javier

**Comment by mscampbell** [comment]
Did it return the variants on the temp.vcf file?
Mike

**Comment by mscampbell** [comment]
From what you described it might be an issue with the header. I added a check in the script to make sure that it is parsing the #CHROM line correctly. Can you try it again?
